# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/pcie/pcie.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie || ORIG_REF_NAME==pcie} -quiet] -quiet

# IP: bd/pcie/ip/pcie_proc_sys_reset_0_0/pcie_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_proc_sys_reset_0_0 || ORIG_REF_NAME==pcie_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_processing_system7_0_0/pcie_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_processing_system7_0_0 || ORIG_REF_NAME==pcie_processing_system7_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_proc_sys_reset_1_0/pcie_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_proc_sys_reset_1_0 || ORIG_REF_NAME==pcie_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_xdma_0_0/pcie_xdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_xdma_0_0 || ORIG_REF_NAME==pcie_xdma_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_xlconstant_0_0/pcie_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_xlconstant_0_0 || ORIG_REF_NAME==pcie_xlconstant_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_xlconstant_1_0/pcie_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_xlconstant_1_0 || ORIG_REF_NAME==pcie_xlconstant_1_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_xlconstant_2_0/pcie_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_xlconstant_2_0 || ORIG_REF_NAME==pcie_xlconstant_2_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_xlconstant_3_0/pcie_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_xlconstant_3_0 || ORIG_REF_NAME==pcie_xlconstant_3_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_util_ds_buf_0_0/pcie_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_util_ds_buf_0_0 || ORIG_REF_NAME==pcie_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_axi_interconnect_0_0/pcie_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_axi_interconnect_0_0 || ORIG_REF_NAME==pcie_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_axi_interconnect_1_0/pcie_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_axi_interconnect_1_0 || ORIG_REF_NAME==pcie_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_axi_bram_ctrl_0_0/pcie_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_axi_bram_ctrl_0_0 || ORIG_REF_NAME==pcie_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_axi_bram_ctrl_1_0/pcie_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_axi_bram_ctrl_1_0 || ORIG_REF_NAME==pcie_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_blk_mem_gen_0_0/pcie_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_blk_mem_gen_0_0 || ORIG_REF_NAME==pcie_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_auto_ds_0/pcie_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_auto_ds_0 || ORIG_REF_NAME==pcie_auto_ds_0} -quiet] -quiet

# IP: bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_auto_pc_0 || ORIG_REF_NAME==pcie_auto_pc_0} -quiet] -quiet

# XDC: bd/pcie/pcie_ooc.xdc
