# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/alexey101/vivado_prj/pcie/pcie.cache/wt [current_project]
set_property parent.project_path /home/alexey101/vivado_prj/pcie/pcie.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.4 [current_project]
set_property ip_output_repo /home/alexey101/vivado_prj/pcie/pcie.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/hdl/pcie_wrapper.v
add_files /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/pcie.bd
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_0_0/pcie_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_0_0/pcie_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_0_0/pcie_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_processing_system7_0_0/pcie_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_1_0/pcie_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_1_0/pcie_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_proc_sys_reset_1_0/pcie_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_0/source/pcie_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_0/synth/pcie_xdma_0_0_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_1/xdma_v4_1_1_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_2/xdma_v4_1_1_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/pcie_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/source/pcie_xdma_0_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_0/synth/pcie_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_util_ds_buf_0_0/pcie_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_util_ds_buf_0_0/pcie_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_util_ds_buf_0_0/pcie_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_axi_bram_ctrl_0_0/pcie_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_axi_bram_ctrl_1_0/pcie_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_blk_mem_gen_0_0/pcie_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_ds_0/pcie_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_ds_0/pcie_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_ds_0/pcie_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/pcie_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/alexey101/vivado_prj/pcie/pcie.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files /home/alexey101/vivado_prj/pcie/pcie.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pcie_wrapper -part xc7z045ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pcie_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pcie_wrapper_utilization_synth.rpt -pb pcie_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
