# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0.xci
# IP: The module: 'pcie_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0.xci
# IP: The module: 'pcie_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexey101/vivado_prj/pcie/pcie.srcs/sources_1/bd/pcie/ip/pcie_auto_pc_0/pcie_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
